create table users
(
    id                uuid    not null
        constraint user_id_pkey
            primary key,
    email             varchar(255),
    password          varchar(255),
    enabled           boolean not null,
    username          varchar(255)
        constraint user_username_key
            unique
);

create table category (id int8 generated by default as identity, title varchar(255), primary key (id));
create table image (id int8 generated by default as identity, image bytea not null, name varchar(255), type varchar(255), product_id int8, primary key (id));
create table product (id int8 generated by default as identity, description varchar(255), price float4 not null, title varchar(255), category_id int8, subcategory_id int8, user_id uuid, primary key (id));
create table subcategory (id int8 generated by default as identity, title varchar(255), category_id int8, primary key (id));

alter table if exists image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product;
alter table if exists product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
alter table if exists product add constraint FKku369nri8u3s17uom8or57trs foreign key (subcategory_id) references subcategory;
alter table if exists product add constraint FK979liw4xk18ncpl87u4tygx2u foreign key (user_id) references users;

create table authorities (
                             username varchar(50) not null,
                             authority varchar(50) not null,
                             constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);

create table oauth_client_details
(
    client_id               varchar(255) not null
        constraint oauth_client_details_client_id_pkey
            primary key,
    access_token_validity   integer,
    additional_information  varchar(255),
    authorities             varchar(255),
    authorized_grant_types  varchar(255),
    autoapprove             boolean      not null,
    client_secret           varchar(255),
    refresh_token_validity  integer,
    resource_ids            varchar(255),
    scope                   varchar(255),
    web_server_redirect_uri varchar(255)
);


-- task-client
INSERT INTO oauth_client_details (client_id,
                                  client_secret,
                                  authorized_grant_types,
                                  scope,
                                  web_server_redirect_uri,
                                  authorities,
                                  access_token_validity,
                                  refresh_token_validity,
                                  additional_information,
                                  autoapprove)
VALUES ('task-client', -- client-id
        '$2a$10$ftGBqfb6LCFoQTbGR8OAf.QGV7e97jwLhboX8OB0OIQzuFH8F5cKa', -- hash client secret: 3vKDcTh5C4
        'password,refresh_token', -- grant types
        'tasks', -- scope
        null,
        null,
        3600,
        36000,
        null,
        true);

-- users, hash of password: password




-- authorities


